export const professions = [
    'React Developer',
    'Angular Developer',
    'Vue.js Developer',
    'Svelte Developer',
    'Next.js Developer',
    'Gatsby Developer',
    'JavaScript Developer',
    'TypeScript Developer',
    'Frontend Architect',
    'Web Performance Engineer',
    'Accessibility Specialist',
    'Progressive Web App Developer',
    'React Native Developer',
    'Flutter Developer',
    'iOS Developer (Swift)',
    'Android Developer (Kotlin)',
    'Cross-platform Mobile Developer',
    'Node.js Developer',
    'Python Developer (Django)',
    'Python Developer (Flask)',
    'Ruby on Rails Developer',
    'Java Developer (Spring)',
    'C# Developer (.NET)',
    'PHP Developer (Laravel)',
    'PHP Developer (Symfony)',
    'Go Developer',
    'Rust Developer',
    'API Developer',
    'Microservices Architect',
    'Full-stack Developer (MERN)',
    'Full-stack Developer (MEAN)',
    'Full-stack Developer (LAMP)',
    'Full-stack Developer (JAMstack)',
    'DevOps Engineer',
    'AWS Architect',
    'Azure Cloud Engineer',
    'Google Cloud Engineer',
    'Kubernetes Administrator',
    'Docker Specialist',
    'CI/CD Engineer',
    'Infrastructure as Code Engineer',
    'Site Reliability Engineer (SRE)',
    'Database Administrator (SQL)',
    'Database Administrator (NoSQL)',
    'MongoDB Developer',
    'PostgreSQL Specialist',
    'Redis Engineer',
    'Elasticsearch Engineer',
    'QA Automation Engineer',
    'Test Architect',
    'Performance Testing Engineer',
    'SDET (Software Development Engineer in Test)',
    'UI Designer (Figma)',
    'UX Designer',
    'UX Researcher',
    'Interaction Designer',
    'Design System Architect',
    'Unity Developer',
    'Unreal Engine Developer',
    'Gameplay Programmer',
    'Game Engine Developer',
    'Blockchain Developer (Solidity)',
    'Web3 Developer',
    'Smart Contract Auditor',
    'Cryptocurrency Analyst',
    'Machine Learning Engineer',
    'Data Scientist',
    'NLP Engineer',
    'Computer Vision Engineer',
    'AI Research Scientist',
    'Data Engineer',
    'ETL Developer',
    'Big Data Engineer',
    'Data Warehouse Architect',
    'Business Intelligence Developer',
    'Cybersecurity Analyst',
    'Penetration Tester',
    'Security Architect',
    'Cryptographer',
    'SOC Analyst',
    'Embedded Systems Developer',
    'IoT Developer',
    'Firmware Engineer',
    'Robotics Programmer',
    'AR Developer',
    'VR Developer',
    'Mixed Reality Engineer',
    'WebGL Developer',
    'Three.js Developer',
    'D3.js Developer',
    'WebAssembly Developer',
    'Electron.js Developer',
    'WordPress Developer',
    'Shopify Developer',
    'Magento Developer',
    'Headless CMS Developer',
    'CTO',
    'Technical Lead',
    'Engineering Manager',
    'Product Manager (Tech)',
    'Project Manager (IT)',
    'Scrum Master',
    'Agile Coach',
    'Technical Writer',
    'Developer Advocate',
    'Content Strategist (Tech)',
    'SEO Specialist (Tech)',
    'Growth Hacker (Tech)',
    'Network Architect',
    'Cloud Network Engineer',
    'VoIP Engineer',
    'Quantum Computing Engineer',
    'FPGA Developer',
    'GPU Programming Specialist',
    'Low-code Developer',
    'No-code Developer',
    'RPA Developer',
    'GIS Developer',
    'Doctor',
    'Lawyer',
    'Teacher',
    'Accountant',
    'Architect',
    'Electrician',
    'Chef',
    'Pilot',
    'Journalist',
    'Psychologist',
    'Nurse',
    'Pharmacist',
    'Financial Analyst',
    'Real Estate Agent',
    'Graphic Designer',
    'Musician',
    'Actor',
    'Athlete',
    'Police Officer',
    'Firefighter',
    'Dentist',
    'Veterinarian',
    'Surgeon',
    'Pediatrician',
    'Psychiatrist',
    'Dermatologist',
    'Optometrist',
    'Physical Therapist',
    'Occupational Therapist',
    'Speech Therapist',
    'Paramedic',
    'Radiologist',
    'Anesthesiologist',
    'Cardiologist',
    'Neurologist',
    'Gynecologist',
    'Urologist',
    'Orthopedic Surgeon',
    'Plastic Surgeon',
    'Dental Hygienist',
    'Medical Assistant',
    'Pharmacy Technician',
    'EMT',
    'Dietitian',
    'Chiropractor',
    'Acupuncturist',
    'Massage Therapist',
    'Podiatrist',
    'Audiologist',
    'Optician',
    'Midwife',
    'Forensic Scientist',
    'Biologist',
    'Chemist',
    'Physicist',
    'Geologist',
    'Meteorologist',
    'Astronomer',
    'Archaeologist',
    'Zoologist',
    'Botanist',
    'Marine Biologist',
    'Environmental Scientist',
    'Geneticist',
    'Microbiologist',
    'Ecologist',
    'Paleontologist',
    'Seismologist',
    'Volcanologist',
    'Hydrologist',
    'Statistician',
    'Economist',
    'Sociologist',
    'Anthropologist',
    'Political Scientist',
    'Historian',
    'Geographer',
    'Linguist',
    'Philosopher',
    'Theologian',
    'Mathematician',
    'Actuary',
    'Market Research Analyst',
    'Operations Research Analyst',
    'Urban Planner',
    'Landscape Architect',
    'Cartographer',
    'Surveyor',
    'Civil Engineer',
    'Mechanical Engineer',
    'Electrical Engineer',
    'Chemical Engineer',
    'Aerospace Engineer',
    'Industrial Engineer',
    'Nuclear Engineer',
    'Biomedical Engineer',
    'Environmental Engineer',
    'Petroleum Engineer',
    'Mining Engineer',
    'Marine Engineer',
    'Agricultural Engineer',
    'Construction Manager',
    'Project Coordinator',
    'Interior Designer',
    'Fashion Designer',
    'Industrial Designer',
    'Jewelry Designer',
    'Floral Designer',
    'Set Designer',
    'Makeup Artist',
    'Photographer',
    'Videographer',
    'Film Director',
    'Animator',
    'Illustrator',
    'Sculptor',
    'Painter',
    'Art Director',
    'Curator',
    'Librarian',
    'Archivist',
    'Museum Technician',
    'Interpreter',
    'Translator',
    'Tour Guide',
    'Flight Attendant',
    'Travel Agent',
    'Event Planner',
    'Wedding Planner',
    'Hotel Manager',
    'Restaurant Manager',
    'Sommelier',
    'Bartender',
    'Barista',
    'Baker',
    'Butcher',
    'Fisherman',
    'Farmer',
    'Rancher',
    'Agricultural Worker',
    'Landscaper',
    'Gardener',
    'Tree Trimmer',
    'Pest Control Worker',
    'Carpenter',
    'Mason',
    'Plumber',
    'Roofer',
    'Glazier',
    'Insulation Worker',
    'Painter (Construction)',
    'Drywall Installer',
    'Tiler',
    'Flooring Installer',
    'HVAC Technician',
    'Welder',
    'Machinist',
    'Tool and Die Maker',
    'Electrician (Industrial)',
    'Auto Mechanic',
] as const;

export type TProfessionsType = (typeof professions)[number];
